[package]
name = "acorus"
version = "0.1.0"
authors = ["khonoka <kagiyamahonoka@pm.me>"]
description = "A tool for managing proxy outbounds."
license = "AGPLv3"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "acorus"

[workspace]
members = []

[dependencies]
lazy_static = "1.4.0"
serde_json = "1.0.68"
termcolor = "1.1.2"
clap = "2.34.0"
log = "0.4.3"
pretty_env_logger = "0.4.0"
base64 = "0.13.0"
tokio = { version = "1.14.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.8"
