[package]
name = "across"
version = "0.1.0"
authors = ["khonoka <kagiyamahonoka@pm.me>"]
description = "A tool for managing proxy outbounds."
license = "AGPLv3"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "across"
path = "crates/core/main.rs"

[workspace]
members = [
    "crates/kernel_manager",
    "crates/latency_test",
    "crates/profile_manager",
    "crates/server",
    "crates/storage",
    "crates/plugin",
    "crates/cli",
]

[dependencies]
clap = { version = "3.0.13", features = ["cargo"] }
lazy_static = "1.4.0"
serde_json = "1.0.78"
termcolor = "1.1.2"
log = "0.4.14"
pretty_env_logger = "0.4.0"
base64 = "0.13.0"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.8"
tonic = "0.6.2"
