[package]
name = "latency_test"
version = "0.1.0"
authors = ["khonoka <kagiyamahonoka@protonmail.com>"]
license = "AGPLv3"
edition = "2018"

[dependencies]
anyhow = "1.0.53"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
