[package]
name = "profile_manager"
version = "0.1.0"
authors = ["khonoka <kagiyamahonoka@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26.3"
anyhow = "1.0.53"
spdlog-rs = "0.1.1"

utils = { path = "../../components/utils" }
