[package]
name = "server"
version = "0.1.0"
authors = ["khonoka <kagiyamahonoka@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spdlog-rs = { version = "0.2.2", features = [
    "level-debug",
    "release-level-info",
] }
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros", "sync"] }
tokio-stream = "0.1.8"
tonic = "0.6.2"
prost = "0.9.0"
anyhow = "1.0.53"
rusqlite = "0.26.3"
reqwest = { version = "0.11.9", features = ["json"]}
base64 = "0.13.0"

profile_manager = { path = "../profile_manager" }
core_protobuf = {path = "../../components/core_protobuf"}

[build-dependencies]
tonic-build = "0.6.2"
