[package]
name = "server"
version = "0.1.0"
authors = ["khonoka <kagiyamahonoka@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spdlog-rs = { version = "0.1.1", features = [
    "level-debug",
    "release-level-info",
] }
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.8"
tonic = "0.6.2"
prost = "0.9.0"
anyhow = "1.0.53"
rusqlite = "0.26.3"

profile-manager = { path = "../profile_manager" }

[build-dependencies]
tonic-build = "0.6.2"
