name: Run Build and Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-bin:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Prepare toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test